require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LendeesController do

  # This should return the minimal set of attributes required to create a valid
  # Lendee. As you add validations to Lendee, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LendeesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lendees as @lendees" do
      lendee = Lendee.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lendees).should eq([lendee])
    end
  end

  describe "GET show" do
    it "assigns the requested lendee as @lendee" do
      lendee = Lendee.create! valid_attributes
      get :show, {:id => lendee.to_param}, valid_session
      assigns(:lendee).should eq(lendee)
    end
  end

  describe "GET new" do
    it "assigns a new lendee as @lendee" do
      get :new, {}, valid_session
      assigns(:lendee).should be_a_new(Lendee)
    end
  end

  describe "GET edit" do
    it "assigns the requested lendee as @lendee" do
      lendee = Lendee.create! valid_attributes
      get :edit, {:id => lendee.to_param}, valid_session
      assigns(:lendee).should eq(lendee)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lendee" do
        expect {
          post :create, {:lendee => valid_attributes}, valid_session
        }.to change(Lendee, :count).by(1)
      end

      it "assigns a newly created lendee as @lendee" do
        post :create, {:lendee => valid_attributes}, valid_session
        assigns(:lendee).should be_a(Lendee)
        assigns(:lendee).should be_persisted
      end

      it "redirects to the created lendee" do
        post :create, {:lendee => valid_attributes}, valid_session
        response.should redirect_to(Lendee.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lendee as @lendee" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lendee.any_instance.stub(:save).and_return(false)
        post :create, {:lendee => { "name" => "invalid value" }}, valid_session
        assigns(:lendee).should be_a_new(Lendee)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lendee.any_instance.stub(:save).and_return(false)
        post :create, {:lendee => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lendee" do
        lendee = Lendee.create! valid_attributes
        # Assuming there are no other lendees in the database, this
        # specifies that the Lendee created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lendee.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => lendee.to_param, :lendee => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested lendee as @lendee" do
        lendee = Lendee.create! valid_attributes
        put :update, {:id => lendee.to_param, :lendee => valid_attributes}, valid_session
        assigns(:lendee).should eq(lendee)
      end

      it "redirects to the lendee" do
        lendee = Lendee.create! valid_attributes
        put :update, {:id => lendee.to_param, :lendee => valid_attributes}, valid_session
        response.should redirect_to(lendee)
      end
    end

    describe "with invalid params" do
      it "assigns the lendee as @lendee" do
        lendee = Lendee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lendee.any_instance.stub(:save).and_return(false)
        put :update, {:id => lendee.to_param, :lendee => { "name" => "invalid value" }}, valid_session
        assigns(:lendee).should eq(lendee)
      end

      it "re-renders the 'edit' template" do
        lendee = Lendee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lendee.any_instance.stub(:save).and_return(false)
        put :update, {:id => lendee.to_param, :lendee => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lendee" do
      lendee = Lendee.create! valid_attributes
      expect {
        delete :destroy, {:id => lendee.to_param}, valid_session
      }.to change(Lendee, :count).by(-1)
    end

    it "redirects to the lendees list" do
      lendee = Lendee.create! valid_attributes
      delete :destroy, {:id => lendee.to_param}, valid_session
      response.should redirect_to(lendees_url)
    end
  end

end
